p "box is #{ENV['TEMPLATE']}"
p "box_url is ../templates/#{ENV['TEMPLATE']}/#{ENV['BOX']}"

Vagrant.configure("2") do |config|
  config.vm.box = "#{ENV['TEMPLATE']}"
  config.vm.box_url = "../templates/#{ENV['TEMPLATE']}/#{ENV['BOX']}"

  config.vm.communicator = "winrm"

  config.winrm.username = "Administrator"
  config.winrm.password = "vagrant"

  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  config.vm.network :forwarded_port, guest: 5985, host: 5985, auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 3389, auto_correct: true

  config.vm.provider :virtualbox do |v, override|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end

  config.vm.provider :vmware_fusion do |v, override|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "1"
  end
end
